INSERT INTO ROLE ( ID, ROLE_NAME, UPDATED_AT, CREATED_AT) VALUES ( nextval('ROLE_SEQ'), 'ADMIN', now(), now() );
INSERT INTO ROLE ( ID, ROLE_NAME, UPDATED_AT, CREATED_AT) VALUES ( nextval('ROLE_SEQ'), 'STAFF', now(), now() );
INSERT INTO ROLE ( ID, ROLE_NAME, UPDATED_AT, CREATED_AT) VALUES ( nextval('ROLE_SEQ'), 'SELECTOR', now(), now() );